### PR TITLE
add zh data

### PR DESCRIPTION
**Pull request by jlwt90**
Hello, I finally added data for simplified chinese (china)!
Could you please check if there is any problem?

Thanks!

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@jlwt90 Great job! All tests passed. Thank you!

**Comment by lk-geimfari** [comment]
@jlwt90 Can you look at README.md, please. It's seems like a table of locales is broken.

**Comment by jlwt90** [comment]
@lk-geimfari hello, it seems that you have already fixed it in [here](https://github.com/lk-geimfari/elizabeth/commit/26c873ec71a3733943fc6dc1e857aa881c37c2f7)? The current locale table looks good i think. Thanks!

**Comment by lk-geimfari** [comment]
@jlwt90 I am sorry. That was my fault.

**Comment by lk-geimfari** [comment]
@jlwt90 Hi! I want to ask you about data which has been added by yourself. I see that you do not added letters of alphabet. It's because you have not alphabet (in Chinese language) or you just forget to add them to file? 

Also, please. Help to understand why sometime tests fails on `zh`:



Thanks in advance!

**Comment by jlwt90** [comment]
> Also, please. Help to understand why sometime tests fails for zh:

Sorry for the mistake! I created #153 

> see that you do not added letters of alphabet. It's because you have not alphabet (in Chinese language) or you just forget to add them to file?

I added english alphabets in this pull request i think. Unlike some other asian languages, e.g. korean, japanese, the foundation of chinese language is **character** (every word in the data files is character,e.g. `长`, `城`, `是`, so I think english alphabet is probably the best choice here coz we sometimes use chinese characters together with english words/characters in daily life.)
https://github.com/jlwt90/elizabeth/blob/5c532c030074c181dbaf1b36d9f8b01e4009d8c3/elizabeth/data/zh/text.json#L2

**Comment by lk-geimfari** [comment]
@jlwt90 I understand you. Thanks!

**Pull request merged**
