### PR TITLE
Added AU states, towns, postcode def, ASX listed companies, new compa…

### PR DESCRIPTION
**Pull request by PaulWaltersDev**
I have added the following -

AU Place Names
AU State names and codes
AU Postcode definition
AU Company Names (all listed ASX companies)
AU Company types Pty Ltd and Trust
All AU universities
A few AU swearwords also corrected spelling of word "bollocks"
Changed spelling of labor and harbor to AU-GB (harbour, labour).

### CODE REVIEW

**Comment by PaulWaltersDev** [comment]
NB: I have included Street suffixes that are the same as those for EN-GB. In almost all cases AU street suffixes are the same as British ones.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Great job! Please, add Australia to [test/locales.py](https://github.com/lk-geimfari/elizabeth/blob/master/tests/test_locales.py) using following format:

```
class AustraliaTest(LocaleBase, TestCase):
    LANG = 'au-en'
```

and run test.

Also, please add your name to [CONTRIBUTORS.md](https://github.com/lk-geimfari/elizabeth/blob/master/CONTRIBUTORS.md)

Thank you!

**Comment by PaulWaltersDev** [comment]
No problem. Will do in the next day.

**Comment by PaulWaltersDev** [comment]
@lk-geimfari  Done. Added reference to en-au in _init_.py, settings.py, _patterns.py and test_locales.py so that the automated tests would pass. No errors. Also added myself to the contributors. Hope these are ok.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Please, add `en-au` to SUPPORTED_LOCALES in [settings.py](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/settings.py)

**Comment by PaulWaltersDev** [comment]
@lk-geimfari sorry forgot to commit that file. Done.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Thanks!

**Pull request merged**
