### PR TITLE
add ko locale data

### PR DESCRIPTION
**Pull request by redus**
here's data for ko locale, i'll commit actual usage pretty soon.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@redus Thank you. Can i merge it? That's all?

**Comment by lk-geimfari** [comment]
@redus Tell me, please where are you from? Which flag we can use for locale `ko`  in README? South Korea?

**Comment by redus** [comment]
from South Korea, and yep south Korean flag for ko. just adding data so shouldn't break anything.

**Comment by lk-geimfari** [comment]
@redus Now i  will run tests. I'll let you know about the result.

**Comment by redus** [comment]
<streetname><street> <number>
is the most common case

**Comment by redus** [comment]
oh it's not showing umm 
[street-name][street] [number]

**Comment by lk-geimfari** [comment]
@redus Good. Thanks!

**Comment by redus** [comment]
yup, I'll improve on address data later, too.

**Pull request merged**
