### PR TITLE
update documentation

### PR DESCRIPTION
**Pull request by wikkiewikkie**
#60 
Also fixed some docstring issues that were causing Sphinx build to throw warnings.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@wikkiewikkie That's really nice work. Thank you!

**Comment by wikkiewikkie** [comment]
@lk-geimfari it looked great when I built it locally, but on readthedocs it seems to have lost the menu on the left and the logo.  Any ideas?

**Comment by lk-geimfari** [comment]
@wikkiewikkie Our documentation is really deprecated (last update is version 0.2.9, when current version is 0.3.11). We need to fully update the documentation, but I have little time and I just can't update documentation because i have not time.

**Comment by lk-geimfari** [comment]
I hope that i can completely update documentation in next week.

**Comment by lk-geimfari** [comment]
@wikkiewikkie As for side-panel, I don't even know.

**Pull request merged**
