### PR TITLE
Added ua locale.

### PR DESCRIPTION
**Pull request by zelds**
Added :
Address
Business
Datetime
Food
Need add:
Personal
Sciene
Text

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@zelds It's looks really awesome! Can you add `ua` to [tests](https://github.com/lk-geimfari/elizabeth/blob/master/tests/conftest.py#L4), please? 

Also, please add data for `ua` to: 
 - [SUPPORTED_LOCALES](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/settings.py#L4)
 - [CURRENCY_SYMBOLS](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/bus.py#L183)
- [ISBN_GROUPS](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/code.py#L33)
- [ROMANIZATION_ALPHABETS](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/dec.py#L2) (here you can read [more](https://github.com/lk-geimfari/elizabeth#decorators))
- Your name to list of our [contributors](https://github.com/lk-geimfari/elizabeth/blob/master/CONTRIBUTORS.md)

Let me know when everything is ready. I'll merge your PR. Thank you.

**Comment by lk-geimfari** [comment]
@zelds I [added](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/dec.py#L115) supporting of Ukrainian for decorator that help latinize Cyrillic text. 

Also has been added:
 - CURRENCY_SYMBOLS
 - ISBN_GROUPS

**Comment by lk-geimfari** [comment]
@zelds I see that you added everything. You made great job! Thank you! Can i merge, or you still work on it?

**Comment by zelds** [comment]
Now not. I just need add one text.json. What is real huge.

**Comment by lk-geimfari** [comment]
@zelds Yes, of course. Thank you.

**Comment by lk-geimfari** [comment]
@zelds Please, look at ISO [639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) specification. `ua` must be `uk`. Correct it, please.

**Pull request merged**
