### PR TITLE
implement sub-locale feature proposed in issue 150

### PR DESCRIPTION
**Pull request by wikkiewikkie**
@lk-geimfari #150

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@wikkiewikkie Very nice. I'll merge your PR and delete all duplicate data for locales which based on other locale. Thank you!

**Comment by lk-geimfari** [comment]
@wikkiewikkie This feature work perfectly. Thanks again.

**Comment by lk-geimfari** [comment]
@wikkiewikkie What if the data in both elbows are absolutely identical? It would be nice if deleting the file for locale did not break anything. For example file datetime.json for `en` and for `en-au` are identical.

**Comment by lk-geimfari** [comment]
@wikkiewikkie I checked it for `en-au` and have some errors. Please, check where is problem, when you'll have a free time. Thanks.

**Comment by wikkiewikkie** [comment]
@lk-geimfari  I think that should take care of it.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Can i merge this PR? Is it done?

**Comment by wikkiewikkie** [comment]
Yes

**Pull request merged**
