### PR TITLE
Extend hungarian language vol.2

### PR DESCRIPTION
**Pull request by uvegla**
* Add hungarian drinks and dishes
* Add hungarian quotes
* Add hungarian text and bad words

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@uvegla Please, [note](https://travis-ci.org/lk-geimfari/elizabeth/builds/203333520). Some tests are not passed.

**Comment by uvegla** [comment]
@lk-geimfari I will have a look in the evening. You can revert it until then, if you see fit, terribly sorry.

**Comment by lk-geimfari** [comment]
@uvegla It's not a problem. I can fix it later. Thanks.

**Comment by uvegla** [comment]
Had a quick look, I believe I left an extra space at the beginning [here](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/data/hu/text.json#L162).

**Comment by lk-geimfari** [comment]
@uvegla Thanks! I'll fix it.

**Pull request merged**
