### PR TITLE
Fixed "# TODO: At this moment this fixture check only english version…

### PR DESCRIPTION
**Pull request by Valerievich**
@lk-geimfari I've fixed "# TODO: At this moment this fixture check only english version of provider." But option option ```--isort``` in pytest.ini didn't work ```py.test: error: unrecognized arguments: --isort```. So I deleted it from config file and then all text_tests passed.  Don't know if it's right.
Please check it.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Valerievich Seems like everything is okay, but you're forget remove `isort` from `.travis.yml`. Please, remove it.

**Comment by lk-geimfari** [comment]
@Valerievich Alos if you are interested, I suggest you look at other tasks:

- https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/mimesis/providers/generic.py#L6
- https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/mimesis/providers/path.py#L13
- https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/mimesis/providers/personal.py#L75

**Comment by Valerievich** [comment]
at this PL ?

**Comment by lk-geimfari** [comment]
@Valerievich In other PR, please.

**Pull request merged**
