### PR TITLE
Feature - PBKDF2 Password Support

### PR DESCRIPTION
**Pull request by JuxhinDB**
Adding support for PBKDF2 password algorithm since certain web apps will enforce that at an ORM level. 

##### Changes

- Added new password algorithm, PBKDF2 with 10K iterations and a random salt
- Updated relevant unittest to also test for new algorithm

All unittests passed, no additional documentation was added as it did not seem needed in this case. 

----

### CODE REVIEW

**Comment by JuxhinDB** [comment]
Regarding this PR (being my first real one), I wanted to add that I intended to add `BCrypt` support as that was my use-case, however as some of you may know this is not including the the standard library and from what I can tell, the project aims to avoid third-party libraries entirely.

**Comment by lk-geimfari** [comment]
@JuxhinDB Thank you for this PR. We try to avoid dependencies from third-party libraries.

**Comment by JuxhinDB** [comment]
@lk-geimfari That's fine. This particular PR makes use of the std lib only.

**Comment by lk-geimfari** [comment]
@JuxhinDB Please, look at Travis CI. It seems like some tests failed.

**Comment by JuxhinDB** [comment]
@lk-geimfari Seems that the project supports 3.3 onward. Unfortunately Python 3.3 does not have `PBKDF2`:

    Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
    >>> import hashlib
    >>> hashlib.algorithms_available
    {'whirlpool', 'sha512', 'SHA1', 'SHA224', 'DSA-SHA', 'sha224', 'MD5', 'SHA512', 'md5', 'SHA384', 
    'dsaEncryption', 'sha', 'SHA', 'md4', 'sha256', 'sha384', 'RIPEMD160', 'DSA', 'sha1', 'ecdsa-with-SHA1', 
    'dsaWithSHA', 'MD4', 'SHA256', 'ripemd160'}

In that case, I suppose we can close this PR. :-)

**Comment by lk-geimfari** [comment]
@JuxhinDB We can not disrupt backward compatibility due to one feature, sorry.

**Pull request closed without merging**
