### PR TITLE
add en-gb support

### PR DESCRIPTION
**Pull request by Uncleleech**
A little confused at the colours in text.json but I copied the 'en' locale for it

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Uncleleech Excellent job! Thank you!

**Comment by lk-geimfari** [comment]
@Uncleleech Can i merge it?

**Comment by Uncleleech** [comment]
For now, unless people want anything changed?
I mean the street name probably could be changed at some point but that's not that important, they're all fairly similar

**Comment by lk-geimfari** [comment]
@Uncleleech Okay.

**Pull request merged**
