### PR TITLE
Bring the code in compliance with the requirements of PEP8

### PR DESCRIPTION
**Pull request by Valerievich**
Code was checked by 'flake8', 'flake8-builtins', 'flake8-commas', 
'flake8-quotes', 'pytest-flake8' and modified folowing the rules

Tests were passed. Local build works well.

*****
flake8 config file
```
[flake8]
ignore = F401, F403, F405
exclude = docs/*, elizabeth/data/*,elizabeth/other/*
```

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Valerievich Excellent job! I will review this PR in the evening, after work. Thank you very much.

**Comment by lk-geimfari** [comment]
@Valerievich Don't forget add yourself to our list of [contributors](https://github.com/lk-geimfari/elizabeth/blob/master/CONTRIBUTORS.md). It's important.

**Comment by Valerievich** [comment]
@lk-geimfari should it be a new PR to add in the list?

**Comment by lk-geimfari** [comment]
@Valerievich Yes, it would be great.

**Pull request merged**
