### PR TITLE
update for ko postal codes

### PR DESCRIPTION
**Pull request by redus**
we've gone through postal code pattern change in near 2015, and i've updated the pattern and tests for it. all tests passing on my end. Thanks for all,

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@redus I'm sorry i didn't know about this. Thank you for PR.

**Comment by redus** [comment]
failing on chemical name test. Korean has elements where the length is less than two, so yeah could be exceptioned with farsi as well

**Comment by redus** [comment]
yup no problem

**Comment by lk-geimfari** [comment]
@redus I fix issue with length of chemical element as son as possible.

**Pull request merged**
